export const SHIPMENT_STATUSES = {
  CREATED: 'created',
  CHINA_WAREHOUSE: 'china_warehouse',
  CHINA_WAREHOUSE_SENT: 'china_warehouse_sent',
  TRANSIT: 'transit',
  ALMATY_WAREHOUSE: 'almaty_warehouse',
  DELIVERED: 'delivered',
};

export const SHIPMENT_STATUSES_ORDERED = [
  SHIPMENT_STATUSES.CREATED,
  SHIPMENT_STATUSES.CHINA_WAREHOUSE,
  SHIPMENT_STATUSES.CHINA_WAREHOUSE_SENT,
  SHIPMENT_STATUSES.TRANSIT,
  SHIPMENT_STATUSES.ALMATY_WAREHOUSE,
  SHIPMENT_STATUSES.DELIVERED,
];
